FROM python:3.9.12
COPY ./Maggie.py /app/
COPY ./requirements.txt /app/

WORKDIR /app/
RUN mkdir General
RUN mkdir Homer
RUN mkdir Lisa
RUN pip3 install -r ./requirements.txt

CMD ["python","Maggie.py"] 


