# docker run  -it python:3.9 bash
# exit 
# docker cp Homer/Homer.csv 53178f0bbe12:/ 
# docker cp Lisa/Lisa.csv 53178f0bbe12:/ 
# docker cp General/General.csv 53178f0bbe12:/ 
# docker start -i 53178f0bbe12 
# mkdir APP
# cd APP 
# mkdir HOMER 
# mkdir LISA 
# mkdir GENERAL 
# cd ..
# mv Homer.csv APP/HOMER 
# mv Lisa.csv APP/LISA 
# mv General.csv APP/GENERAL 
# cd APP 
# ls
# cd HOMER
# ls
# cat Homer.csv


